let a = Number(prompt("Введите первое число - "))
let b = Number(prompt("Введите второе число - "))
alert(a + b)
alert(a - b)
alert(a * b)
alert(a / b)
alert(a ** b)
let multi = 8
alert("8 * 1 = " + multi * 1)
alert("8 * 2 = " + multi * 2)
alert("8 * 3 = " + multi * 3)
alert("8 * 4 = " + multi * 4)
alert("8 * 5 = " + multi * 5)
alert("8 * 6 = " + multi * 6)
alert("8 * 7 = " + multi * 7)
alert("8 * 8 = " + multi * 8)
alert("8 * 9 = " + multi * 9)
alert("8 * 10 = " + multi * 10)